update deprecated comment in read me
hps/heartland-magento-extension pull request #141
Opened 2024-11-12 10:39 UTC by tsysamit

update deprecated comment in read me

2024-11-12 10:45 UTC, tsysamit commented
Please review this PR

2024-11-12 14:01 UTC, tsysamit commented
Please close other PR as well

2024-11-12 14:55 UTC, MSmedal requested changes

2024-11-13 05:40 UTC, tsysamit commented
@MSmedal  I have approved the changes suggested by you.

2024-11-25 17:27 UTC, merged